version: '3.8'

services:
  k3s-server:
    image: rancher/k3s:latest
    command: server
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
    privileged: true
    restart: always
    environment:
    - K3S_TOKEN=SECRET
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    - K3S_CLUSTER_INIT=true
    - K3S_DISABLE=traefik,servicelb,metrics-server
    volumes:
    - k3s-server:/var/lib/rancher/k3s
    - ./k3s-config:/output
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - "6443:6443"  # Kubernetes API server
    - "80:80"      # HTTP
    - "443:443"    # HTTPS
    - "30000-30010:30000-30010"  # NodePort range
    networks:
    - k3s-net

volumes:
  k3s-server: {}

networks:
  k3s-net:
    driver: bridge
