apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.yaml: |
    service:
      flush: 5
      log_level: info
      daemon: off
      parsers_file: parsers.conf
      http_server: true
      http_listen: 0.0.0.0
      http_port: 2020

    pipeline:
      inputs:
        - name: tail
          path: /var/log/containers/high-volume-logger-*.log
          parser: cri
          tag: kube.*
          refresh_interval: 5
          mem_buf_limit: 50MB
          skip_long_lines: true
          skip_empty_lines: true

          processors:
            logs:
              - name: kubernetes
                alias: kube_processor
                kube_url: https://kubernetes.default.svc:443
                kube_ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                kube_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
                kube_tag_prefix: kube.var.log.containers.
                merge_log: true
                keep_log: false
                k8s-logging.parser: true
                k8s-logging.exclude: true
                annotations: false
                labels: true
                kube_meta_preload_cache_dir: /fluent-bit/kube-meta-preload

              - name: lua
                alias: lua_processor
                script: /fluent-bit/etc/process_logs.lua
                call: process_record

      outputs:
        # run tail -f /var/fluent-bit-logs/processed-logs.log on the host
        - name: file
          match: "*"
          path: /fluent-bit/logs/
          file: processed-logs.log
          format: plain

  parsers.conf: |
    [PARSER]
        # http://rubular.com/r/tjUt3Awgg4
        Name cri
        Format regex
        Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

    [PARSER]
        Name   logfmt
        Format logfmt

  process_logs.lua: |
    function process_record(tag, timestamp, record)
        -- Verify the log line was parsed
        -- print(record.seq2)

        -- Remove any key-value pair not starting with "seq"
        for key, _ in pairs(record) do
          if string.sub(key, 1, 3) ~= "seq" then
              record[key] = nil
          end
        end

        return 1, timestamp, record
    end
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    app: fluent-bit
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
      annotations:
        fluentbit.io/exclude: "true"
    spec:
      serviceAccountName: fluent-bit
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:3.2.2-debug
        command:
          - /fluent-bit/bin/fluent-bit
        args:
          - --config=/fluent-bit/etc/fluent-bit.yaml
        ports:
        - containerPort: 2020
          name: http
          protocol: TCP
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
        - name: fluent-bit-logs
          mountPath: /fluent-bit/logs/
        - name: cache-dir
          mountPath: /fluent-bit/kube-meta-preload/
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            cpu: 20m
            memory: 256Mi
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      - name: fluent-bit-logs
        hostPath:
          path: /var/fluent-bit-logs
          type: DirectoryOrCreate
      - name: cache-dir
        hostPath:
          path: /tmp/kube-meta-preload
          type: DirectoryOrCreate
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-read
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-read
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: logging
---
apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    app: fluent-bit
spec:
  type: NodePort
  ports:
  - port: 2020
    targetPort: 2020
    nodePort: 30020
    name: http
  selector:
    app: fluent-bit
