apiVersion: apps/v1
kind: Deployment
metadata:
  name: high-volume-logger
  namespace: default
  labels:
    app: high-volume-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: high-volume-logger
  template:
    metadata:
      labels:
        app: high-volume-logger
    spec:
      containers:
      - name: logger
        image: alpine:latest
        command: ["/bin/sh"]
        args:
          - -c
          - |
            while true; do
              for i in $(seq 1 1000); do
                for j in $(seq 1 1000); do
                  # Generate 1,000 log lines
                  yes "seq1=$i seq2=$j - log from $HOSTNAME" | head -1000
                  sleep 0.1
                done
                sleep 60
              done
            done
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
