apiVersion: apps/v1
kind: Deployment
metadata:
  name: high-volume-logger
  namespace: default
  labels:
    app: high-volume-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: high-volume-logger
  template:
    metadata:
      labels:
        app: high-volume-logger
    spec:
      containers:
      - name: logger
        image: alpine:latest
        command: ["/bin/sh"]
        args:
          - -c
          - |
            while true; do
              # Generate 10,000 log lines
              yes "$(date) - Burst log from $HOSTNAME" | head -10000
              sleep 0.001
            done
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
